brand:
  name: Top
menu-string: Menu

nav:
  - title: Projects
    url: '#portfolio'
  - title: About
    url: '#about'
  - title: Contact
    url: '#contact'
  - title: Resume
    url: '/assets/resume.pdf'
  - title: Publications
    url: '/publications.md'

copyright: Copyright &copy; Your Website 2018

social-buttons:
  - icon: fa fa-twitter
    url: 'https://twitter.com/gaurijagatap' 
  - icon: fa fa-linkedin
    url: 'https://www.linkedin.com/in/gauri-jagatap'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
