brand:
  name: Gauri Jagatap
menu-string: Menu

nav:
  - title: About
    url: '#about'
  - title: Projects
    url: '#portfolio'
  - title: Contact
    url: '#contact'
  - title: Resume
    url: '/assets/resume.pdf'
  - title: Publications
    url: 'https://scholar.google.com/citations?user=B7-TNaIAAAAJ&hl=en'

copyright: Copyright &copy; Gauri Jagatap 2019

social-buttons:
  - icon: fa fa-twitter
    url: 'https://twitter.com/gaurijagatap' 
  - icon: fa fa-linkedin
    url: 'https://www.linkedin.com/in/gauri-jagatap'
  - icon: fa fa-github
    url: 'https://www.github.com/gaurijagatap'
  - icon: fa fa-envelope
    url: 'mailto:gauri@iastate.edu'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'

